# Generated by Django 2.1 on 2018-08-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
    ]
